// ─── Engine Types ─────────────────────────────────────────────────────
// All shared TypeScript interfaces for the AI Test Engineer pipeline.

/** A single exported function discovered by the analyzer. */
export interface ScannedFunction {
    filePath: string;
    functionName: string;
    functionCode: string;
}

/** An existing test file found in the project. */
export interface ExistingTest {
    filePath: string;
    fileName: string;
}

/** A test file generated by the LLM. */
export interface GeneratedTest {
    functionName: string;
    testFilePath: string;
    testCode: string;
}

/** Summary of test execution results. */
export interface TestResult {
    total: number;
    passed: number;
    failed: number;
}

/** Parsed coverage information. */
export interface CoverageResult {
    totalLines: number;
    coveredLines: number;
    percentage: number;
}

/** Final result returned by the orchestrator to the API. */
export interface EngineResult {
    coverage: number;
    totalTests: number;
    passed: number;
    failed: number;
    logs: string[];
}

/** Structured error thrown by engine stages. */
export class EngineError extends Error {
    public readonly stage: string;

    constructor(stage: string, message: string) {
        super(message);
        this.name = 'EngineError';
        this.stage = stage;
    }
}
